modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
logoFile="assets/zenkai/banner.png"
authors="${mod_authors}"
description='''${mod_description}'''

# NeoForge
[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="${neo_version_range}"
ordering="NONE"
side="BOTH"

# Minecraft
[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

# GeckoLib
[[dependencies.${mod_id}]]
modId="geckolib"
type="required"
reason="Necesario para animaciones de entidades y modelos 3D"
versionRange="[4.8.4,)"
ordering="AFTER"
side="BOTH"

# Curios API
[[dependencies.${mod_id}]]
modId="curios"
type="required"
reason="Las pesas de entrenamiento y el scouter usan slots de Curios"
versionRange="[9.0.0,)"
ordering="AFTER"
side="BOTH"

# TerraBlender
[[dependencies.${mod_id}]]
modId="terrablender"
type="required"
reason="Necesario para la generación de biomas y mundo"
versionRange="[4.1.0.8,)"
ordering="AFTER"
side="BOTH"

# Player Animation Lib
[[dependencies.${mod_id}]]
modId = "player_animation_library"
type = "required"
reason = "Necesario para las animaciones del jugador"
versionRange = "[1.1.5,)"
ordering = "AFTER"
side = "BOTH"

# Configured (opcional)
[[dependencies.${mod_id}]]
modId="configured"
type="optional"
reason="Añade la pantalla de configuración con acceso a common y server desde la lista de mods"
versionRange="[2.6.3,)"
ordering="AFTER"
side="CLIENT"

[modproperties.${mod_id}]
catalogueImageIcon="assets/zenkai/icon.png"
catalogueBackground = "assets/zenkai/background.png"

[[mixins]]
config="assets/zenkai/zenkai.mixins.json"